REM 文字列の表示(putchar)
REM CODE環境変数に表示したい文字列の番号
REM NOWSTRが用いらえれる
IF "%CODE%"=="10" (
	REM 空白だった場合改行しないと
	SET IS_SPACE=0
	IF "%NOWSTR%"=="" SET IS_SPACE=1
	IF "%NOWSTR%"==" " SET IS_SPACE=1
	IF "%NOWSTR%"=="  " SET IS_SPACE=1
	IF "%NOWSTR%"=="   " SET IS_SPACE=1
	IF "%NOWSTR%"=="    " SET IS_SPACE=1
)
IF "%CODE%"=="10" (
	IF "%IS_SPACE%"=="0" (
		ECHO %NOWSTR%
	) ELSE (
		ECHO.
	)
	SET NOWSTR=
) 
IF "%CODE%"=="32" (
	SET NOWSTR=%NOWSTR% 
) ELSE IF "%CODE%"=="33" (
	SET NOWSTR=%NOWSTR%!
) ELSE IF "%CODE%"=="34" (
	SET NOWSTR=%NOWSTR%”
) ELSE IF "%CODE%"=="35" (
	SET NOWSTR=%NOWSTR%#
) ELSE IF "%CODE%"=="36" (
	SET NOWSTR=%NOWSTR%$
) ELSE IF "%CODE%"=="37" (
	SET NOWSTR=%NOWSTR%％
) ELSE IF "%CODE%"=="38" (
	SET NOWSTR=%NOWSTR%＆
) ELSE IF "%CODE%"=="39" (
	SET NOWSTR=%NOWSTR%'
) ELSE IF "%CODE%"=="40" (
	SET NOWSTR=%NOWSTR%（
) ELSE IF "%CODE%"=="41" (
	SET NOWSTR=%NOWSTR%）
) ELSE IF "%CODE%"=="42" (
	SET NOWSTR=%NOWSTR%*
) ELSE IF "%CODE%"=="43" (
	SET NOWSTR=%NOWSTR%+
) ELSE IF "%CODE%"=="44" (
	SET NOWSTR=%NOWSTR%,
) ELSE IF "%CODE%"=="45" (
	SET NOWSTR=%NOWSTR%-
) ELSE IF "%CODE%"=="46" (
	SET NOWSTR=%NOWSTR%.
) ELSE IF "%CODE%"=="47" (
	SET NOWSTR=%NOWSTR%/
) ELSE IF "%CODE%"=="48" (
	SET NOWSTR=%NOWSTR%0
) ELSE IF "%CODE%"=="49" (
	SET NOWSTR=%NOWSTR%1
) ELSE IF "%CODE%"=="50" (
	SET NOWSTR=%NOWSTR%2
) ELSE IF "%CODE%"=="51" (
	SET NOWSTR=%NOWSTR%3
) ELSE IF "%CODE%"=="52" (
	SET NOWSTR=%NOWSTR%4
) ELSE IF "%CODE%"=="53" (
	SET NOWSTR=%NOWSTR%5
) ELSE IF "%CODE%"=="54" (
	SET NOWSTR=%NOWSTR%6
) ELSE IF "%CODE%"=="55" (
	SET NOWSTR=%NOWSTR%7
) ELSE IF "%CODE%"=="56" (
	SET NOWSTR=%NOWSTR%8
) ELSE IF "%CODE%"=="57" (
	SET NOWSTR=%NOWSTR%9
) ELSE IF "%CODE%"=="58" (
	SET NOWSTR=%NOWSTR%:
) ELSE IF "%CODE%"=="59" (
	SET NOWSTR=%NOWSTR%;
) ELSE IF "%CODE%"=="60" (
	SET NOWSTR=%NOWSTR%＜
) ELSE IF "%CODE%"=="61" (
	SET NOWSTR=%NOWSTR%=
) ELSE IF "%CODE%"=="62" (
	SET NOWSTR=%NOWSTR%＞
) ELSE IF "%CODE%"=="63" (
	SET NOWSTR=%NOWSTR%?
) ELSE IF "%CODE%"=="64" (
	SET NOWSTR=%NOWSTR%@
) ELSE IF "%CODE%"=="65" (
	SET NOWSTR=%NOWSTR%A
) ELSE IF "%CODE%"=="66" (
	SET NOWSTR=%NOWSTR%B
) ELSE IF "%CODE%"=="67" (
	SET NOWSTR=%NOWSTR%C
) ELSE IF "%CODE%"=="68" (
	SET NOWSTR=%NOWSTR%D
) ELSE IF "%CODE%"=="69" (
	SET NOWSTR=%NOWSTR%E
) ELSE IF "%CODE%"=="70" (
	SET NOWSTR=%NOWSTR%F
) ELSE IF "%CODE%"=="71" (
	SET NOWSTR=%NOWSTR%G
) ELSE IF "%CODE%"=="72" (
	SET NOWSTR=%NOWSTR%H
) ELSE IF "%CODE%"=="73" (
	SET NOWSTR=%NOWSTR%I
) ELSE IF "%CODE%"=="74" (
	SET NOWSTR=%NOWSTR%J
) ELSE IF "%CODE%"=="75" (
	SET NOWSTR=%NOWSTR%K
) ELSE IF "%CODE%"=="76" (
	SET NOWSTR=%NOWSTR%L
) ELSE IF "%CODE%"=="77" (
	SET NOWSTR=%NOWSTR%M
) ELSE IF "%CODE%"=="78" (
	SET NOWSTR=%NOWSTR%N
) ELSE IF "%CODE%"=="79" (
	SET NOWSTR=%NOWSTR%O
) ELSE IF "%CODE%"=="80" (
	SET NOWSTR=%NOWSTR%P
) ELSE IF "%CODE%"=="81" (
	SET NOWSTR=%NOWSTR%Q
) ELSE IF "%CODE%"=="82" (
	SET NOWSTR=%NOWSTR%R
) ELSE IF "%CODE%"=="83" (
	SET NOWSTR=%NOWSTR%S
) ELSE IF "%CODE%"=="84" (
	SET NOWSTR=%NOWSTR%T
) ELSE IF "%CODE%"=="85" (
	SET NOWSTR=%NOWSTR%U
) ELSE IF "%CODE%"=="86" (
	SET NOWSTR=%NOWSTR%V
) ELSE IF "%CODE%"=="87" (
	SET NOWSTR=%NOWSTR%W
) ELSE IF "%CODE%"=="88" (
	SET NOWSTR=%NOWSTR%X
) ELSE IF "%CODE%"=="89" (
	SET NOWSTR=%NOWSTR%Y
) ELSE IF "%CODE%"=="90" (
	SET NOWSTR=%NOWSTR%Z
) ELSE IF "%CODE%"=="91" (
	SET NOWSTR=%NOWSTR%[
) ELSE IF "%CODE%"=="92" (
	SET NOWSTR=%NOWSTR%\
) ELSE IF "%CODE%"=="93" (
	SET NOWSTR=%NOWSTR%]
) ELSE IF "%CODE%"=="94" (
	SET NOWSTR=%NOWSTR%＾
) ELSE IF "%CODE%"=="95" (
	SET NOWSTR=%NOWSTR%_
) ELSE IF "%CODE%"=="96" (
	SET NOWSTR=%NOWSTR%`
) ELSE IF "%CODE%"=="97" (
	SET NOWSTR=%NOWSTR%a
) ELSE IF "%CODE%"=="98" (
	SET NOWSTR=%NOWSTR%b
) ELSE IF "%CODE%"=="99" (
	SET NOWSTR=%NOWSTR%c
) ELSE IF "%CODE%"=="100" (
	SET NOWSTR=%NOWSTR%d
) ELSE IF "%CODE%"=="101" (
	SET NOWSTR=%NOWSTR%e
) ELSE IF "%CODE%"=="102" (
	SET NOWSTR=%NOWSTR%f
) ELSE IF "%CODE%"=="103" (
	SET NOWSTR=%NOWSTR%g
) ELSE IF "%CODE%"=="104" (
	SET NOWSTR=%NOWSTR%h
) ELSE IF "%CODE%"=="105" (
	SET NOWSTR=%NOWSTR%i
) ELSE IF "%CODE%"=="106" (
	SET NOWSTR=%NOWSTR%j
) ELSE IF "%CODE%"=="107" (
	SET NOWSTR=%NOWSTR%k
) ELSE IF "%CODE%"=="108" (
	SET NOWSTR=%NOWSTR%l
) ELSE IF "%CODE%"=="109" (
	SET NOWSTR=%NOWSTR%m
) ELSE IF "%CODE%"=="110" (
	SET NOWSTR=%NOWSTR%n
) ELSE IF "%CODE%"=="111" (
	SET NOWSTR=%NOWSTR%o
) ELSE IF "%CODE%"=="112" (
	SET NOWSTR=%NOWSTR%p
) ELSE IF "%CODE%"=="113" (
	SET NOWSTR=%NOWSTR%q
) ELSE IF "%CODE%"=="114" (
	SET NOWSTR=%NOWSTR%r
) ELSE IF "%CODE%"=="115" (
	SET NOWSTR=%NOWSTR%s
) ELSE IF "%CODE%"=="116" (
	SET NOWSTR=%NOWSTR%t
) ELSE IF "%CODE%"=="117" (
	SET NOWSTR=%NOWSTR%u
) ELSE IF "%CODE%"=="118" (
	SET NOWSTR=%NOWSTR%v
) ELSE IF "%CODE%"=="119" (
	SET NOWSTR=%NOWSTR%w
) ELSE IF "%CODE%"=="120" (
	SET NOWSTR=%NOWSTR%x
) ELSE IF "%CODE%"=="121" (
	SET NOWSTR=%NOWSTR%y
) ELSE IF "%CODE%"=="122" (
	SET NOWSTR=%NOWSTR%z
) ELSE IF "%CODE%"=="123" (
	SET NOWSTR=%NOWSTR%{
) ELSE IF "%CODE%"=="124" (
	SET NOWSTR=%NOWSTR%｜
) ELSE IF "%CODE%"=="125" (
	SET NOWSTR=%NOWSTR%}
) ELSE IF "%CODE%"=="126" (
	SET NOWSTR=%NOWSTR%~
)

